### ISSUE TITLE
Update fence_ovh to becom python3 compliant

### ISSUE THREAD

**Issue by gqdc** [adriangibanelbtactic/fence-agents#1]
I've installed the version of fence_ovh, which is compliant with "OVH API V6", and it runs like a charm.
But, it would be better if the agent were compliant with pyton3.

By the way, thanks a lot for your work ! :)

**Comment by adriangibanelbtactic** [comment]
Thank you for your nice words.

I no longer maintain this repo/script.

You should check the newest: https://github.com/ClusterLabs/fence-agents repo instead.
